### ISSUE TITLE
meta: Use unity builds by default

### ISSUE THREAD

**Issue by coletrammer** [ColeTrammer/os_2#137]
# Summary

Currently, the default build presets are not unity builds. This is required because the the `compile_commands.json` for the unity builds does not play nicely with clangd. The solution is to generate a `compile_commands.json` from a non-unity build, but actually use a unity build internally. To do this, we need to generate a lot of cmake build presets, and this will be done programmatically, by writing a simple JSON generator. This will also "fix" the large amount of copy-pasting needed to add a new configure/build/test preset.

# Progress

- [x] Implement CMake preset generator
- [x] Copy better compile_commands.json for unity builds
- [x] Change default build presets
- [x] Remove references to CMAKE_UNITY_BUILD from CI and scripts
