### ISSUE TITLE
di: Simplify meta-programming around index sequence and nontype

### ISSUE THREAD

**Issue by coletrammer** [ColeTrammer/os_2#175]
# Summary

Currently, there are types like integral constant, which require specifying the first argument as the type parameter. It would be simpler to have only a single type of this kind, which takes its value as auto. For instance, instead of using `meta::bool_constant<true>` we could instead write `meta::c_<true>`. IntegerSequence can also be more general and hold any pack of values. This would follow 

# Progress

- [x] Add Constexpr type
- [x] Replace integral constant
- [x] Replace integral sequence
- [x] Replace in place index
- [x] Replace nontype
- [x] Add tests
