### ISSUE TITLE
di: Make type-erased classes constexpr

### ISSUE THREAD

**Issue by coletrammer** [ColeTrammer/os_2#217]
# Summary

GCC 13 and clang 17 implement constexpr cast from `void*`, which enables compile time type erasure.

# Progress

- [x] Upgrade to clang 17
- [x] Upgrade to gcc 14
- [x] Make `di::Any` constexpr
- [x] Simplify `di::present` constexpr support
- [x] Make tests constexpr
