### ISSUE TITLE
meta: Setup CI

### ISSUE THREAD

**Issue by coletrammer** [ColeTrammer/os_2#37]
# Summary

To make the system much more robust, it will be helpful to enable continuous integration. This is easy enough to do for Linux builds, but will require some work to also run unit tests under Iros.

# Progress

- [X] Parse basic kernel command line to configure which start program to run
- [X] Get unit tests running under Iros
- [x] Setup CI on Linux
  - [x] Make sure to build with sanitizers
- [x] Setup CI on Iros
  - [x] Cache the Iros toolchain in somehow (most likely in a docker image)
  - [x] Configure CMAKE_CROSSCOMPILING_EMULATOR to be able to run programs under Iros
    - [x] This will involve creating a boot image and initrd for the target program
  - [x] Successfully run the unit tests in CI
- [x] Require PRs to successfully pass CI before merging
- [x] Add status badges to README.md
- [x] Make the toolchain CI build available for users in a dev container, so that the Iros will be easily buildable for anyone, without having to compile a toolchain for 30 minutes
