### ISSUE TITLE
meta: Generate and publish auto-documentation

### ISSUE THREAD

**Issue by coletrammer** [ColeTrammer/os_2#45]
# Summary

Currently, there is some design documents in markdown under the `docs/` subdirectory, but there is no per-code documentation. And having random markdown files is not easy to navigate.

We can generate documentation using Doxygen, and make it look presentable by using this [theme](https://jothepro.github.io/doxygen-awesome-css/). And lastly, the documentation can be automatically built and deployed using GitHub pages.

Hopefully, using this mechanism will work very well. It is also possible that generating separate sites for each library will work better. But I think Doxygen can be configured to generate modules somehow.

Alternatives which were considered include (hdoc)[https://hdoc.io/] and (mdBook)[https://rust-lang.github.io/mdBook/index.html]. hdoc unfortunately generates terrible output, most likely because clang does not seem to understand requires clauses. mdBook is great for displaying the existing documentation but would require code documentation be on a separate site with completely different theming. With Doxygen, the 2 can be combined and it generates reasonable output.

# Progress

- [x] Setup Doxygen documentation locally
- [x] Build docs in CI
- [x] Setup Doxygen Awesome theme
- [x] Deploy docs using GitHub pages
- [x] Link docs in README and GitHub panel
- [x] Link overview of Iris kernel for justification on why this project exists
