### ISSUE TITLE
meta: Support building the project with clang

### ISSUE THREAD

**Issue by coletrammer** [ColeTrammer/os_2#67]
# Summary

Currently, the system can only be built using GCC. This unfortunately means that clangd is unusable, since it clang fails to compile the source code. Clang additionally catches many things that GCC doesn't, like more instances unused variables, and offers clang-tidy for linting.

Note that we don't need a custom version of clang which understands iros yet, but clang just needs to be able to compile the code when __iros__ is set to 1.

# Progress

-   [x] Compile with clang
-   [x] Use clangd
-   [x] Test with clang in CI
-   [ ] Fix clang compiling execution
-   [ ] Fix clang compiling linux io_uring async backend
